### PR TITLE
Change location of sponsors on index.html

### PR DESCRIPTION
**Pull request by ladyleet**
Changed the location of sponsors on the index.html template. Added some mpadding to keep design consistent. Jorge, if you need to edit this a bit, go ahead

### CODE REVIEW

**Comment by ladyleet** [comment]
@jorgelainfiesta 👍 ?

**Comment by jorgelainfiesta** [comment]
Looks ok!

**Comment by ladyleet** [comment]
i'll let you merge if it's good

**Comment by jorgelainfiesta** [comment]
Ok, I'll deploy it

**Comment by ladyleet** [comment]
WOOT

**Pull request merged**
